name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Katmandu
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 20
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_traffic: yes
          plugin_contributors: yes
          plugin_contributors_contributions: yes
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors-graphs, os-graphs
          plugin_wakatime_days: 365
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://medium.com/feed/@aayushchalise
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_music: yes
          plugin_music_limit: 4
          plugin_music_mode: playlist
          plugin_music_played_at: yes
          plugin_music_playlist: https://music.youtube.com/playlist?list=PL7Qi33wZIPOFIy_01WVHqB2NdLYBVdZzi
          plugin_music_provider: youtube
          plugin_music_time_range: medium
          plugin_music_top_type: tracks
          plugin_music_user: https://music.youtube.com/@aayushxvf
