name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          
          token: ${{ secrets.METRICS_TOKEN }}

          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Katmandu
          config_display: large
          plugin_activity: yes
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 20
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_traffic: yes
          plugin_contributors: yes
          plugin_contributors_contributions: yes
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base, repositories
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, editors-graphs, os, os-graphs
          plugin_wakatime_days: 365
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_gists: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: pull_request
          plugin_notable_self: yes
          plugin_notable_indepth: no
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          plugin_languages_limit: 8
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8
          plugin_repositories: yes
          plugin_repositories_featured: harilvfs/carch, harilvfs/blog-site, harilvfs/dwm, harilvfs/web
          plugin_repositories_affiliations: owner, collaborator
          plugin_licenses: yes
          plugin_rss: yes
          plugin_rss_source: https://archlinux.org/feeds/news/
          plugin_rss_limit: 4
