name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Katmandu
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 20
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          plugin_traffic: yes
          plugin_contributors: yes
          plugin_contributors_contributions: yes
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_topics: yes
          plugin_topics_limit: 50
          plugin_topics_mode: icons
          plugin_topics_sort: stars
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors-graphs, os-graphs
          plugin_wakatime_days: 365
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_rss: yes
          plugin_rss_limit: 4
          plugin_rss_source: https://medium.com/feed/@aayushchalise
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_gists: yes
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit,pull_request,issue
          plugin_notable_self: yes
          plugin_notable_indepth: no
          plugin_notable_repositories: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          plugin_languages_limit: 10
          plugin_discussions: yes
          plugin_discussions_categories_limit: 10
