name: Update Activity Status

on:
  schedule:
    # Run every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch: # Allow manual trigger
    
jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Use your PAT for authentication
          token: ${{ secrets.PAT }}
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Create .env file
        run: |
          echo "GITHUB_TOKEN=${{ secrets.PAT }}" > .env
          echo "USERNAME=${{ github.repository_owner }}" >> .env
      
      - name: Install dependencies
        run: npm install axios dotenv
      
      - name: Create status script
        run: |
          cat > update-status.js <<'EOF'
          require('dotenv').config();
          const fs = require('fs');
          const axios = require('axios');
          
          const username = process.env.USERNAME;
          const token = process.env.GITHUB_TOKEN;
          
          // Catppuccin colors
          // Using Mocha palette
          const CATPPUCCIN_GREEN = "ABE9B3" // Green for online
          const CATPPUCCIN_RED = "F28FAD"   // Red for offline
          
          async function getLastActivityTime() {
            try {
              const response = await axios.get(
                `https://api.github.com/users/${username}/events`,
                {
                  headers: {
                    Authorization: `token ${token}`,
                    'User-Agent': 'Activity-Status-Updater'
                  }
                }
              );
              
              if (response.data && response.data.length > 0) {
                return new Date(response.data[0].created_at);
              }
              return null;
            } catch (error) {
              console.error('Error fetching GitHub activity:', error.message);
              return null;
            }
          }
          
          async function updateReadmeTemplate() {
            try {
              // Get last activity time
              const lastActivity = await getLastActivityTime();
              const now = new Date();
              const timeDiffMinutes = lastActivity ? 
                Math.floor((now - lastActivity) / (1000 * 60)) : null;
              
              // Determine status - online if active in the last 15 minutes
              const isOnline = timeDiffMinutes !== null && timeDiffMinutes < 15;
              
              // Catppuccin themed badge with for-the-badge style
              const onlineBadge = `![Status](https://img.shields.io/badge/Status-Online-${CATPPUCCIN_GREEN}?style=for-the-badge&logo=github&logoColor=white)`;
              const offlineBadge = `![Status](https://img.shields.io/badge/Status-Offline-${CATPPUCCIN_RED}?style=for-the-badge&logo=github&logoColor=white)`;
              const statusBadge = isOnline ? onlineBadge : offlineBadge;
              
              // Read current README.gtpl
              const templatePath = 'README.gtpl';
              if (!fs.existsSync(templatePath)) {
                console.error('README.gtpl not found');
                return;
              }
              
              const template = fs.readFileSync(templatePath, 'utf8');
              
              // Match the entire section while preserving the exact content format
              const badgeSection = template.match(/(<!--Badge\s*-->[\s\S]*?<!-- badge _END -->)/i);
              
              if (badgeSection) {
                // Get the exact original text with correct spacing and formatting
                const originalSection = badgeSection[0];
                
                // Create new section with badge replacing "the badges should be here" (preserve line breaks)
                const newSection = originalSection.replace(
                  /the badges should be here/, 
                  statusBadge
                );
                
                // Replace entire section in the template
                const newTemplate = template.replace(originalSection, newSection);
                
                // Write updated template
                fs.writeFileSync(templatePath, newTemplate);
                console.log(`Updated status in README.gtpl to ${isOnline ? 'Online' : 'Offline'}`);
              } else {
                console.error('Badge markers not found in README.gtpl');
              }
              
              console.log(`Last activity: ${lastActivity ? lastActivity.toISOString() : 'Unknown'}`);
            } catch (error) {
              console.error('Error updating README.gtpl:', error.message);
            }
          }
          
          updateReadmeTemplate();
          EOF
      
      - name: Execute status script
        run: node update-status.js
        
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.gtpl
          git diff --quiet && git diff --staged --quiet || git commit -m "Update activity status in README template"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git push
